import type { Metadata } from "next";
import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackgroundDots from "@/components/BackgroundDots";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Danny Amezquita, UX engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">{`
          try {
            var stored = localStorage.getItem('theme');
            var prefersLight = window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches;
            var t = stored || (prefersLight ? 'light' : 'dark');
            var html = document.documentElement;
            if (t === 'dark') {
              html.classList.add('dark');
              html.removeAttribute('data-theme');
            } else {
              html.classList.remove('dark');
              html.setAttribute('data-theme', 'light');
            }
          } catch (e) {}
        `}</Script>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <BackgroundDots count={140} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
