import type { Metadata } from "next";
import Script from "next/script";
import { Plus_Jakarta_Sans, Geist_Mono, Instrument_Serif, Zen_Loop } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import BackgroundDots from "@/components/BackgroundDots";
import ScrollProgress from "@/components/ScrollProgress";
import CursorSpotlight from "@/components/CursorSpotlight";

const plusJakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const instrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});

const zenLoop = Zen_Loop({
  variable: "--font-zen-loop",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Danny Amezquita, UX engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light" suppressHydrationWarning>
      <head>
        <Script id="theme-init" strategy="beforeInteractive">{`
          try {
            var stored = localStorage.getItem('theme');
            var prefersDark = window.matchMedia && window.matchMedia('(prefers-color-scheme: dark)').matches;
            var t = stored || (prefersDark ? 'dark' : 'light');
            var html = document.documentElement;
            if (t === 'dark') {
              html.classList.add('dark');
              html.removeAttribute('data-theme');
            } else {
              html.classList.remove('dark');
              html.setAttribute('data-theme', 'light');
            }
          } catch (e) {}
        `}</Script>
      </head>
      <body className={`${plusJakartaSans.variable} ${geistMono.variable} ${instrumentSerif.variable} ${zenLoop.variable} antialiased overflow-x-hidden`}>
        <ScrollProgress />
        <CursorSpotlight />
        <BackgroundDots count={140} />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
